### ISSUE TITLE
Build Instructions

### ISSUE THREAD

**Issue by flumonion** [mozey/ts#2]
Following the instructions in the readme for the http example:

```
cd ts/http
./build.sh
```

Results in:

```
-bash: tsc: command not found
```

It may be obvious that you need TypeScript installed to run TypeScript examples in a repos called ts :) 
Perhaps consider adding instructions to install TypeScript for those who are new to the language.

```
npm install -g typescript
```

**Comment by mozey** [comment]
https://www.typescriptlang.org/
